name = "tataoro-gpt"
compatibility_date = "2025-05-18"
main = "workers/router.js"
route = "https://wa.tataoro.com/*"

[[kv_namespaces]]
binding = "CHAT_HISTORY"
id = "d153e5f2f8fd404e8e7778c494396215"

[[kv_namespaces]]
binding = "DOC_KNOWLEDGE"
id = "c4281158fd7346fdac1f9e10bc092079"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "tataoro-chat-images"
preview_bucket_name = "tataoro-chat-images"

[vars]
EMAIL_ENABLED = true
EMAIL_PROVIDER = "resend"
EMAIL_FROM = "consultations@tataoro.com"
EMAIL_TO = "tatacurly@tataoro.com"
SHOPIFY_STORE_DOMAIN = "tataoro.com"
WHATSAPP_BASE_URL = "https://wa.tataoro.com"

[observability.logs]
enabled = true
