
name = "tataoro-gpt"
compatibility_date = "2025-05-18"
main = "workers/whatsapp.js"

[[kv_namespaces]]
binding = "CHAT_HISTORY"
id = "d153e5f2f8fd404e8e7778c494396215"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "tataoro-chat-images"
preview_bucket_name = "tataoro-chat-images"

[[kv_namespaces]]
binding = "DOC_KNOWLEDGE"
id = "c4281158fd7346fdac1f9e10bc092079"

[env.whatsapp]
main = "workers/whatsapp.js"
name = "tataoro-whatsapp"
route = "https://wa.tataoro.com/*"

[env.docsync]
main = "workers/doc-sync.js"
name = "tataoro-doc-sync"
# Trigger via cron or CLI — no route needed

[env.uploadhook]
main = "workers/upload-hook.js"
name = "tataoro-upload-hook"
route = "https://tataoro.com/uploadhook"

[env.scheduler]
main = "workers/scheduler.js"
name = "tataoro-scheduler"
triggers = { crons = ["0 * * * *"] }

[vars]
EMAIL_ENABLED = true
EMAIL_PROVIDER = "resend"
EMAIL_FROM = "consultations@tataoro.com"
EMAIL_TO = "tatacurly@tataoro.com"
RESEND_API_KEY = "<your-resend-api-key>"
SHOPIFY_STORE_DOMAIN = "<your-shopify-store-domain>"
SHOPIFY_API_TOKEN = "<your-shopify-api-token>"
TWILIO_WHATSAPP_NUMBER = "whatsapp:<your-twilio-whatsapp-number>"

[observability.logs]
enabled = true