name = "tataoro-whatsapp-gpt"
main = "index.js"  # adjust if it's elsewhere
compatibility_date = "2025-05-18"

[[kv_namespaces]]
binding = "CHAT_HISTORY"
id = "d153e5f2f8fd404e8e7778c494396215"

[[r2_buckets]]
binding = "MEDIA_BUCKET"       # This is how you'll reference it in code (env.MEDIA_BUCKET)
bucket_name = "tataoro-chat-images"   # Name of your R2 bucket
preview_bucket_name = "tataoro-chat-images"  # Optional but often mirrors bucket_name

[observability.logs]
enabled = true